version: '3.7'

services:
  armonik.control.submitter:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  armonik.control.metrics:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  armonik.compute.pollingagent0:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Amqp__PartitionId=TestPartition0
      - Submitter__DefaultPartition=TestPartition0
    ports:
      - 9980:1080
    volumes:
      - socket_vol0:/cache

  armonik.compute.pollingagent1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Amqp__PartitionId=TestPartition1
      - Submitter__DefaultPartition=TestPartition1
    ports:
      - 9981:1080
    volumes:
      - socket_vol1:/cache

  armonik.compute.worker0:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 1080:1080
    volumes:
      - socket_vol0:/cache

  armonik.compute.worker1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 1081:1080
    volumes:
      - socket_vol1:/cache
