version: '3.7'

services:
  armonik.control:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
      - "443"

  armonik.compute.pollingagent:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development