version: '3.7'

services:
  queue:
    image: rabbitmq:3-management
    command: sh -c "echo [rabbitmq_management,rabbitmq_management_agent]. > /etc/rabbitmq/enabled_plugins && exec docker-entrypoint.sh rabbitmq-server"
    networks:
      - armonik-backend
    ports:
      - 127.0.0.1:5672:5672
      - 15672:15672

  armonik.control.submitter:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.control.metrics:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.control.partitionmetrics:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent0:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest      
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent1:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2

  armonik.compute.pollingagent2:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
      - Amqp__Host=queue
      - Amqp__Port=5672
      - Amqp__Scheme=AMQP
      - Amqp__MaxPriority=10
      - Amqp__MaxRetries=10
      - Amqp__LinkCredit=2