version: '3.7'

services:
  armonik.control:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  armonik.compute.pollingagent:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  armonik.compute.worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
