version: '3.7'

services:
  queue:
    image: rabbitmq:3-management
    command: sh -c "echo [rabbitmq_management,rabbitmq_management_agent,rabbitmq_amqp1_0]. > /etc/rabbitmq/enabled_plugins && exec docker-entrypoint.sh rabbitmq-server"
    networks:
      - armonik-backend
    ports:
      - 127.0.0.1:5672:5672
      - 15672:15672

  armonik.control.submitter:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest

  armonik.control.metrics:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest

  armonik.compute.pollingagent:
    environment:
      - Amqp__User=guest
      - Amqp__Password=guest
