name: DeployTest

on:
  push:
    paths:
      - 'Adaptors/**'
      - 'Common/**'
      - 'Compute/**'
      - 'Control/**'
      - 'Stream/**'
      - 'Tests/**'
      - '.github/workflows/**'
    branches:
      - '**'

jobs:
  versionning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.genver.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Generate Version
      id: genver
      run: |
        VERSION=$(docker run --rm -v $(pwd):/repo codacy/git-version /bin/git-version --folder=/repo --release-branch=release --dev-branch=master) 
        echo "::set-output name=version::$VERSION"
        echo $VERSION

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        projects:
          - Common/tests
          - Adaptors/MongoDB/tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Run tests
      run: |
        cd ${{ matrix.projects }}
        dotnet test --logger "trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test - ${{ matrix.projects }}
        path: ${{ matrix.projects }}/TestResults/test-results.trx
        reporter: dotnet-trx

  buildProjects:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    # find . -name "*.csproj" | xargs -I % echo dotnet build % -c Release
    - name: Build the projects
      run: |
        dotnet build ./Adaptors/Amqp/src/ArmoniK.Core.Adapters.Amqp.csproj -c Release
        dotnet build ./Adaptors/Memory/src/ArmoniK.Core.Adapters.Memory.csproj -c Release
        dotnet build ./Adaptors/Memory/tests/ArmoniK.Core.Adapters.Memory.Tests.csproj -c Release
        dotnet build ./Adaptors/MongoDB/src/ArmoniK.Core.Adapters.MongoDB.csproj -c Release
        dotnet build ./Adaptors/MongoDB/tests/ArmoniK.Core.Adapters.MongoDB.Tests.csproj -c Release
        dotnet build ./Adaptors/Redis/src/ArmoniK.Core.Adapters.Redis.csproj -c Release
        dotnet build ./Common/src/ArmoniK.Core.Common.csproj -c Release
        dotnet build ./Common/tests/ArmoniK.Core.Common.Tests.csproj -c Release
        dotnet build ./Compute/PollingAgent/src/ArmoniK.Core.Compute.PollingAgent.csproj -c Release
        dotnet build ./Control/Metrics/src/ArmoniK.Core.Control.Metrics.csproj -c Release
        dotnet build ./Control/Submitter/src/ArmoniK.Core.Control.Submitter.csproj -c Release
        dotnet build ./Control/Submitter/tests/ArmoniK.Core.Control.Submitter.Tests.csproj -c Release

  buildImages:
    runs-on: ubuntu-latest
    needs:
      - versionning
      - buildProjects
      - tests
    env:
      VERSION: ${{ needs.versionning.outputs.version }}
    strategy:
      fail-fast: true
      matrix:
        include:
        -  img : dockerhubaneo/armonik_pollingagent
           path: ./Compute/PollingAgent/src/Dockerfile
        -  img : dockerhubaneo/armonik_control_metrics
           path: ./Control/Metrics/src/Dockerfile
        -  img : dockerhubaneo/armonik_control
           path: ./Control/Submitter/src/Dockerfile
        -  img : dockerhubaneo/armonik_core_stream_test_worker
           path: ./Tests/Stream/Server/Dockerfile
        -  img : dockerhubaneo/armonik_core_stream_test_client
           path: ./Tests/Stream/Client/Dockerfile
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        submodules: true

    - name: login
      run: |
        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u dhaneo1 --password-stdin

    - name: Build
      run: |
        echo $VERSION
        docker build -t ${{ matrix.img }}:$VERSION -f ${{ matrix.path }} .

    - name: push
      run: |
        docker push ${{ matrix.img }}:$VERSION

  testStream:
    needs:
      - versionning
      - buildImages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          submodules: true

      - uses: aneoconsulting/ArmoniK@main
        id: deploy-infra
        with:
          control-plane-image: dockerhubaneo/armonik_control
          control-plane-tag: ${{ needs.versionning.outputs.version }}
          polling-agent-image: dockerhubaneo/armonik_pollingagent
          polling-agent-tag: ${{ needs.versionning.outputs.version }}
          worker-image: dockerhubaneo/armonik_core_stream_test_worker
          worker-tag: ${{ needs.versionning.outputs.version }}
          log-level: Information

      - name: Run Stream Tests
        timeout-minutes: 15
        run: |
         export CPIP=$(kubectl get svc control-plane -n armonik -o custom-columns="IP:.spec.clusterIP" --no-headers=true)
         export CPPort=$(kubectl get svc control-plane -n armonik -o custom-columns="PORT:.spec.ports[*].port" --no-headers=true)
         export Grpc__Endpoint=http://$CPIP:$CPPort

         cd ./Tests/Stream/Client/
         dotnet test --logger "trx;LogFileName=test-results.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test - Stream
          path: ./Tests/Stream/Client/TestResults/test-results.trx
          reporter: dotnet-trx

      - name: Copy logs
        if: always()
        shell: bash
        run: |
          set -e
          mkdir -p /tmp/armoniklogs
          sudo cp -rL /var/log/pods/armonik_* /tmp/armoniklogs
          sudo chown $USER -R /tmp/armoniklogs
          find /tmp/armoniklogs -name "*.log"

      - name: Store logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Logs Stream
          path: /tmp/armoniklogs/**/*.log
          retention-days: 5

  testStreamDockerCompose:
    needs:
      - versionning
      - buildImages
    env:
      VERSION: ${{ needs.versionning.outputs.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        queue:
          - activemqp
          - artemis
          - rabbitmq
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          submodules: true
      - name: Docker compose up
        run: |
          export ARMONIK_WORKER=dockerhubaneo/armonik_core_stream_test_worker:$VERSION
          export ARMONIK_METRICS=dockerhubaneo/armonik_control_metrics:$VERSION
          export ARMONIK_SUBMITTER=dockerhubaneo/armonik_control:$VERSION
          export ARMONIK_POLLINGAGENT=dockerhubaneo/armonik_pollingagent:$VERSION
          docker-compose -f docker-compose/docker-compose.yml -f docker-compose/docker-compose.queue-${{ matrix.queue }}.yml up -d --build --force-recreate --remove-orphans

      - name: Run Stream Test
        run: |
          cd ./Tests/Stream/Client/
          dotnet test --logger "trx;LogFileName=test-results.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test - ${{ matrix.queue }}
          path: ./Tests/Stream/Client/TestResults/test-results.trx
          reporter: dotnet-trx

  tag:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/release' }}
    needs:
      - versionning
      - testStream
    env:
      VERSION: ${{ needs.versionning.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: tag
      run: |
        git tag $VERSION
        git push origin $VERSION
