name: Code Formatting

on:
  pull_request:

jobs:
  format-csharp:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      with:
        ref: ${{ github.ref }}

    - name: Install .NET Core
      uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4
      with:
        dotnet-version: 8.x

    - name: Install ReSharper
      run: |
        dotnet tool install -g JetBrains.ReSharper.GlobalTools --version 2022.3.3

    - name: Restore
      run: |
        dotnet restore ArmoniK.Core.sln

    - name: Reformat
      run: |
        jb cleanupcode --profile="Full Cleanup With Headers" ArmoniK.Core.sln

    - name: Check Diff
      id: check-diff
      run: |
        DIFF="$(git diff --name-only)"

        if [ -z "$DIFF" ]; then
          echo "OK: Format is clean"
        else
          echo "Error: Format was not clean"
          echo "List of files:"
          echo "$DIFF"
          git diff
          exit 1
        fi

    - name: Generate patch
      if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
      run: |
        git diff > patch-csharp.diff

    - uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4
      if: ${{ failure() && steps.check-diff.conclusion == 'failure' }}
      with:
        name: patch-csharp
        path: ./patch-csharp.diff

  format-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          ref: ${{ github.ref }}

      - name: Check Format
        run: terraform fmt -check -recursive -diff


  mode-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      with:
        ref: ${{ github.ref }}

    - name: Set files mode to 644
      run: git grep -l "" | grep -v -E "\.sh$" | xargs chmod 644

    - name: Check Diff
      id: check-diff
      run: |
        DIFF="$(git diff --name-only)"

        if [ -z "$DIFF" ]; then
          echo "OK: Files mode is clean"
        else
          echo "Error: Files mode was not clean"
          echo "List of files:"
          echo "$DIFF"
          git diff
          exit 1
        fi