name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  versionning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.snapshot.outputs.version }}
      release: ${{ steps.release.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Remove tag locally
    # This is done so that codacy/git-version can compute the version of the images deployed on docker hub
      run: |
        git tag -d ${{ github.ref_name }}

    - name: Compute branch for codacy
    # This is the branch to give to codacy to compute the snapshot version
      id: rev
      run: |
        export CURRENT_BRANCH=$(git describe --tags)
        echo "current-branch=$CURRENT_BRANCH" >> $GITHUB_OUTPUT

    - name: Generate Snapshot Version
      id: snapshot
      uses: codacy/git-version@80c816f11db8dea5e3a81025f598193015b51832 # 2.8.0
      with:
        minor-identifier: "feat:"
        release-branch: ${{ github.ref_name }}-pre
        dev-branch: ${{ steps.rev.outputs.current-branch }}

    - name: Generate Release Version
      id: release
      uses: codacy/git-version@80c816f11db8dea5e3a81025f598193015b51832 # 2.8.0
      with:
        minor-identifier: "feat:"
        release-branch: ${{ steps.rev.outputs.current-branch }}
        dev-branch: main

    - name: Put versions in step summary
      run: |
        echo SNAPSHOT => ${{ steps.snapshot.outputs.version }} >> $GITHUB_STEP_SUMMARY
        echo RELASE   => ${{ steps.release.outputs.version }} >> $GITHUB_STEP_SUMMARY

    - name: Validate tag
      run : test ${{ steps.release.outputs.version }} == ${{ github.ref_name }}

    - name: Delete tag if invalid
      if: failure() || cancelled()
      run : git push origin -d ${{ github.ref_name }}


  images:
    runs-on: ubuntu-latest
    needs:
      - versionning
    env:
      VERSION: ${{ needs.versionning.outputs.release }}
    strategy:
      fail-fast: true
      matrix:
        type:
          - build-core
          - buildBenchClient
          - worker=bench buildWorker
          - buildStreamClient
          - worker=stream buildWorker
          - buildHtcmockClient
          - worker=htcmock buildWorker
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        ref: ${{ github.ref }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

    - name: Setup just
      run: sudo snap install --edge --classic just

    - name: login
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_LOGIN }} --password-stdin

    - name: Build
      run: just tag=$VERSION platform=linux/arm64,linux/amd64 load=false push=true ${{ matrix.type }}


  publish-nuget:
    runs-on: ubuntu-latest
    needs:
      - versionning
    env:
      VERSION: ${{ needs.versionning.outputs.release }}
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        ref: ${{ github.ref }}

    - name: Build the package
      run: |
        dotnet build Base/src/ArmoniK.Core.Base.csproj -c Release

    - name: Pack the package
      run: |
        dotnet pack Base/src/ArmoniK.Core.Base.csproj -c Release -o /tmp/packages -p:PackageVersion=$VERSION -p:Version=$VERSION

    - name: Push the package
      run: dotnet nuget push /tmp/packages/ArmoniK.Core.*.nupkg -k ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json


  update-changelog:
    runs-on: ubuntu-latest
    needs:
      - versionning
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 18

      - run: npx @aneoconsultingfr/order-github-release-notes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
