name: Scout Images

on:
    schedule:
      - cron: '10 9 * * 1'   # 9:10 on Monday
    workflow_dispatch:

jobs:
  releases:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.releases.outputs.releases }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: List last releases
      id: releases
      run: echo "releases=$(gh release list -L 3 --json tagName -q '[ .[].tagName ]')"  >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ github.token }}

  scout:
    runs-on: ubuntu-latest
    needs: releases
    strategy:
      fail-fast: false
      matrix:
        image:
          - pollingagent
          - control_metrics
          - control_partition_metrics
          - control
          - core_stream_test_worker
          - core_stream_test_client
          - core_htcmock_test_worker
          - core_htcmock_test_client
          - core_bench_test_worker
          - core_bench_test_client
        version: ${{ fromJSON(needs.releases.outputs.releases) }}
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Pull image
      run: docker pull "dockerhubaneo/armonik_${{ matrix.image }}:${{ matrix.version }}"
    - name: Analyze for critical and high CVEs
      uses: docker/scout-action@aceeb83b88f2ae54376891227858dda7af647183 # v1
      with:
        command: cves
        image: "dockerhubaneo/armonik_${{ matrix.image }}:${{ matrix.version }}"
        sarif-file: "${{ matrix.image }}_${{ matrix.version }}.sarif.json"
        summary: true
        platform: linux/amd64
    - name: print sarif file
      run: cat "${{ matrix.image }}_${{ matrix.version }}.sarif.json"
