name: Scout Images

on:
    schedule:
      - cron: '10 9 * * 1'   # 9:10 on Monday
    workflow_dispatch:

jobs:
  releases:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.releases.outputs.releases }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: List last releases
      id: releases
      run: echo "releases:$(gh release list -L 3 --json tagName -q '[ .[].tagName ]')"  >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ github.token }}

  scout:
    runs-on: ubuntu-latest
    needs: releases
    strategy:
      fail-fast: false
      matrix:
        image:
          - dockerhubaneo/armonik_pollingagent
          - dockerhubaneo/armonik_control_metrics
          - dockerhubaneo/armonik_control_partition_metrics
          - dockerhubaneo/armonik_control
          - dockerhubaneo/armonik_core_stream_test_worker
          - dockerhubaneo/armonik_core_stream_test_client
          - dockerhubaneo/armonik_core_htcmock_test_worker
          - dockerhubaneo/armonik_core_htcmock_test_client
          - dockerhubaneo/armonik_core_bench_test_worker
          - dockerhubaneo/armonik_core_bench_test_client
        version: ${{ fromJSON(needs.releases.outputs.releases) }}
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
      with:
        username: ${{ secrets.DOCKER_HUB_LOGIN }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Analyze for critical and high CVEs
      uses: docker/scout-action@b23590dc1e4d09febc00cfcbc51e9e8c0f7ee9f3 # v1
      with:
        command: cves
        image: "${{ matrix.image }}:${{ matrix.image }}"
        sarif-file: "${{ matrix.image }}_${{ matrix.image }}.sarif.json"
        summary: true
        platform: linux/arm64,linux/amd64,windows/amd64
    - name: print sarif file
      run: cat "${{ matrix.image }}_${{ matrix.image }}.sarif.json"
